export const trekkingItem = [
  {
    id: 1,
    type: 'rent',
    name: 'Jaket Outdoor',
    price: 10000,
    image: '/items/jaket-outdoor.png',
  },
  {
    id: 2,
    type: 'rent',
    name: 'Topi Rimba',
    price: 5000,
    image: '/items/topi-rimba.png',
  },
  {
    id: 3,
    type: 'rent',
    name: 'Golok',
    price: 20000,
    image: '/items/golok.png',
  },
  {
    id: 4,
    type: 'rent',
    name: 'Pisau Lipat',
    price: 10000,
    image: '/items/pisau-lipat.png',
  },
  {
    id: 5,
    type: 'rent',
    name: 'Sepatu Gunung',
    price: 25000,
    image: '/items/sepatu-outdoor.png',
  },
  {
    id: 6,
    type: 'rent',
    name: 'Sleeping Bag',
    price: 20000,
    image: '/items/sleeping-bag.png',
  },
  {
    id: 7,
    type: 'rent',
    name: 'Matras',
    price: 10000,
    image: `/items/matras.png`,
  },
  {
    id: 8,
    type: 'rent',
    name: 'Tenda',
    price: 50000,
    image: '/items/tenda.png',
  },
  {
    id: 9,
    type: 'rent',
    name: 'Senter',
    price: 15000,
    image: '/items/senter.png',
  },
  {
    id: 10,
    type: 'rent',
    name: 'Lampu Darurat',
    price: 25000,
    image: '/items/lampu-emergency.png',
  },
  {
    id: 11,
    type: 'rent',
    name: 'Drybag',
    price: 30000,
    image: '/items/drybag.png',
  },
  {
    id: 12,
    type: 'rent',
    name: 'Carrier',
    price: 35000,
    image: '/items/carrier.png',
  },
  {
    id: 13,
    type: 'rent',
    name: 'Kompor Camping',
    price: 15000,
    image: '/items/kompor-outdoor.png',
  },
  {
    id: 14,
    type: 'rent',
    name: 'Nesting',
    price: 15000,
    image: '/items/nesting.png',
  },
  {
    id: 15,
    type: 'rent',
    name: 'Tongkat Jalan',
    price: 15000,
    image: '/items/tongkat-jalan.png',
  },
  { id: 16, type: 'rent', name: 'GPS', price: 50000, image: '/items/gps.png' },
]

export const packetItem = [
  {
    id: 17,
    type: 'sale',
    name: 'Paket P3K',
    price: 50000,
    image: '/items/p3k.png',
  },
  {
    id: 18,
    type: 'sale',
    name: 'Trashbag',
    price: 5000,
    image: '/items/trashbag.png',
  },
  {
    id: 19,
    type: 'sale',
    name: 'Korek',
    price: 5000,
    image: '/items/korek.png',
  },
  {
    id: 20,
    type: 'sale',
    name: 'Selimut Darurat',
    price: 50000,
    image: '/items/emergency-blanket.png',
  },
  {
    id: 21,
    type: 'sale',
    name: 'Kaos Kaki Outdoor',
    price: 25000,
    image: '/items/kaos-kaki-outdoor.png',
  },
]
