import NavigationBar from '@/components/ui/navigation-bar-footer/navigation-bar/navigation-bar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/ui/navigation-bar-footer/footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NavigationBar />
      <body className={inter.className}>{children}</body>
      <Footer />
    </html>
  )
}
